### ISSUE TITLE
Access evalulator apps

### ISSUE THREAD

**Issue by ShankarQlik** [qlik-oss/qlik-cloud-access-evaluator#10]
under access evauation sheet -> App access -> this visualization is displaying "the request exceeds memory limit".

<img width="958" alt="memory exceed" src="https://github.com/qlik-oss/qlik-cloud-access-evaluator/assets/158261668/e76a1df1-7245-4912-8589-9d73a11bc072">

**Comment by withdave** [comment]
Hi @ShankarQlik 

Thanks for the issue, we suggest making a selection for several spaces to reduce the data shown in the table, or modifying to remove any columns you don't use. We'll leave the in-app table with all columns in, however, to make it easier for others to customize in future.
